version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme123!
      POSTGRES_DB: crashnburn
    ports:
      - 5432:5432
  backend:
    depends_on:
      - db
    image: crashnburn-backend
    build: ./backend
    ports:
      - 8080:8080
